server:
  port: 8081

spring:
  application:
    name: college-server
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${college.datasource.driver-class-name}
    url: jdbc:mysql://${college.datasource.host}:${college.datasource.port}/${college.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${college.datasource.username}
    password: ${college.datasource.password}

  data:
    redis:
      host: ${college.data.redis.host}
      port: ${college.data.redis.port}
      password: ${college.data.redis.password}
      lettuce:
        pool:
          max-active: ${college.data.redis.lettuce.pool.max-active}
          max-idle: ${college.data.redis.lettuce.pool.max-idle}
          min-idle: ${college.data.redis.lettuce.pool.min-idle}
          time-between-eviction-runs: ${college.data.redis.lettuce.pool.time-between-eviction-runs}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: a311.college.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 设置日志级别
logging:
  level:
    a311:
      college:
        server: info
        mapper: debug
        controller: info

# 设置JWT令牌
college:
  jwt:
    # 设置jwt签名加密使用的密钥
    user-secret-key: collegeCritic
    # 设置JWT令牌过期时间
    user-time: 7200000
    # 设置前端请求传递的令牌名称
    user-token-name: token



knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表
  basic:
    enable: true
    username: admin
    password: 123456
